version: '3'

services:
  app:
    build: .
    image: atlas:0.92
    restart: unless-stopped
    user: shiny
    ports:
    - "4242:3838"
    depends_on:
    - dbP007Demo
    - dbP009Demo
  dbP007Demo:
    image: postgres:10-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - "./P007Demo.sql.gz:/docker-entrypoint-initdb.d/P007Demo.sql.gz:z"
  dbP009Demo:
    image: postgres:10-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - "./P009Demo.sql.gz:/docker-entrypoint-initdb.d/P009Demo.sql.gz:z"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    links:
      - "dbP007Demo:pgsql-serverP007"
      - "dbP009Demo:pgsql-serverP009"
