FROM python:3.10
LABEL mainteiner "Jian Liu <Jian.liu@plantandfood.co.nz>"

ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code

COPY requirements.txt /code/
RUN pip install --upgrade pip setuptools wheel
RUN pip install -r requirements.txt
COPY . /code/
